JarrydWorland/2021_Capstone_GP2_Team

MicrowaveGame2D/Assets/1. Scenes/SampleScene.unity
MicrowaveGame2D/Assets/3. Scripts/PlayerMovement.cs
MicrowaveGame2D/Assets/3. Scripts/PlayerMovement.cs.meta
MicrowaveGame2D/Assets/Inputs.meta
MicrowaveGame2D/Assets/Inputs/MicrowaveGame2D.inputactions
MicrowaveGame2D/Assets/Inputs/MicrowaveGame2D.inputactions.meta
MicrowaveGame2D/Packages/manifest.json
MicrowaveGame2D/ProjectSettings/PackageManagerSettings.asset
MicrowaveGame2D/ProjectSettings/ProjectSettings.asset
MicrowaveGame2D/ProjectSettings/TimelineSettings.asset

Basil: I have done some tests on the input system, and verified native colliders are working.
Movement is working.

Player movement

---

MicrowaveGame2D/Assets/Prefabs/Speed PowerUp.prefab
MicrowaveGame2D/Assets/Prefabs/Speed PowerUp.prefab.meta
MicrowaveGame2D/Assets/Scenes/PowerUpSystemTestScene.unity
MicrowaveGame2D/Assets/Scenes/PowerUpSystemTestScene.unity.meta
MicrowaveGame2D/Assets/Scenes/SampleScene.unity
MicrowaveGame2D/Assets/Scripts/Player/PlayerMovement.cs
MicrowaveGame2D/Assets/Scripts/PowerUpSpeed.cs
MicrowaveGame2D/Assets/Scripts/PowerUpSpeed.cs.meta

if statement fixes here, inital power up created.

Power up system

---

MicrowaveGame2D/Assets/Scripts/Player/PlayerMovement.cs
MicrowaveGame2D/Assets/Scripts/PowerUpSpeed.cs

main got updated before the Effects-Duration Branch was finished. I took my changes from the Effect-Durations Branch, made a new branch based on main, and I checked if my changes still applied. They do.

Updated Effects-Duration Based on main after PlayerMovement Update.

---

MicrowaveGame2D/Assets/Prefabs/Player.prefab
MicrowaveGame2D/Assets/Scripts/Player/PlayerMovement.cs
MicrowaveGame2D/Assets/Scripts/Player/PlayerShootBehaviour.cs
MicrowaveGame2D/Assets/Scripts/Weapons/BaseWeapon.cs

You're now able to aim when using a controller, horray!
Shooting animation updates are now in the correct script.

Allow aiming with the right stick on a controller

---

MicrowaveGame2D/Assets/Prefabs/Doors/DoorEastStyle1.prefab
MicrowaveGame2D/Assets/Prefabs/Doors/DoorNorthStyle1.prefab
MicrowaveGame2D/Assets/Prefabs/Doors/DoorSouthStyle1.prefab
MicrowaveGame2D/Assets/Prefabs/Doors/DoorWestStyle1.prefab

Adjusted the colliders on the doors to ensure they are always overlapping over the walls.

Adjusted door colliders

---

MicrowaveGame2D/Assets/Resources/ROOMS/Room_SW.prefab
MicrowaveGame2D/Assets/Resources/ROOMS/Room_SW.prefab.meta
MicrowaveGame2D/Assets/Scripts/Level/LevelGenerator.cs
MicrowaveGame2D/Assets/Scripts/Level/LevelManager.cs

- Added an option to the LevelManager to always show rooms, this should be helpful for debugging. (14870ee859d3aaec720562169efa22f2e3589861)
- Adjusted the room spacing to reduce camera motion, addressing feedback on motion sickness. (f1c7a8256bbcfe1ad0f9ff63c3861e1c5d528c01)
- Added missing room prefab to satiate level generator (e34c1fb79f53a04fa6258b394fe95aa0b27acfe1)

Room adjustments

---

MicrowaveGame/Assets/Resources/Prefabs/Items/ItemSpeedIncrease.prefab
MicrowaveGame/Assets/Resources/Prefabs/Player/Player.prefab
MicrowaveGame/Assets/Resources/Scripts/Items/ItemSpeedIncreaseBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Player/PlayerMovementBehaviour.cs

- Added velocity and friction (46ed700)
- The velocity should be reset when hitting solid objects, however colliders are not in this branch.
Place the player and level objects and move around.

Refactor player movement

---

MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuControls.prefab
MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuCredits.prefab
MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuDeath.prefab
MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuPaused.prefab
MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuPlaying.prefab
MicrowaveGame/Assets/Resources/Scenes/Gameplay.unity
MicrowaveGame/Assets/Resources/Scripts/Inventory/InventoryBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuMainBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuManager.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuNarrativeBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuPausedBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuPlayingBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Player/PlayerDeathBehaviour.cs

This PR adjusts the playing menu in order to resolve some issues we were facing.

Refactor menu adjustments

---

MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedE.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedES.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedESW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedEW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedN.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedNE.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedNES.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedNEW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedNS.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedNSW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedNW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedS.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedSW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedW.prefab

This PR populates all room prefabs (with the exception of the base room and the NESW room) with enemies and hazards.
To test, simply play the game!

Populate rooms with enemies and hazards

---

MicrowaveGame/Assets/Resources/Materials/Sprites-Additive.mat
MicrowaveGame/Assets/Resources/Materials/Sprites-Additive.mat.meta
MicrowaveGame/Assets/Resources/Materials/Sprites-Additive.shader
MicrowaveGame/Assets/Resources/Materials/Sprites-Additive.shader.meta
MicrowaveGame/Assets/Resources/Prefabs/Enemies/EnemyLamp.prefab
MicrowaveGame/Assets/Resources/Prefabs/Player/Player.prefab
MicrowaveGame/Assets/Resources/Scripts/HealthBehaviour.cs

- Added flash effect (507d169)
- Added sorting group to player (1b4881e)
- Raised player sprite order (bec82ff)
Play and ensure player and enemy sprites flash when they receive damage.

Refactor flash

---

MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomBase.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomPlated/RoomPlatedBase.prefab
MicrowaveGame/Assets/Resources/Scripts/Items/ItemHealthIncreaseBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Items/ItemSpeedIncreaseBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Rooms/RoomClearBehaviour.cs

- Fixed error on room clear (9467570)
Play and ensure no room related errors occur.

Fixed error on room clear

---

MicrowaveGame/Assets/Resources/Scripts/Enemies/EnemyLamp/EnemyLampShootBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Utilities/Extensions.cs

- Fixed lamp animation blending (335c1f1)
Ensure the lamp does not spawn two projectiles at once when he fires at the player.

Fixed lamp animation blending

---

MicrowaveGame/Assets/Resources/Prefabs/SceneFader.prefab
MicrowaveGame/Assets/Resources/Prefabs/SceneFader.prefab.meta
MicrowaveGame/Assets/Resources/Scenes/Gameplay.unity
MicrowaveGame/Assets/Resources/Scenes/Menu.unity
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuDeathBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuMainBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuPausedBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/SceneFader.cs
MicrowaveGame/Assets/Resources/Scripts/SceneFader.cs.meta

Fade transition between scenes.

Scene fader implementation

---

MicrowaveGame/Assets/Resources/Scripts/Levels/LevelGenerator.cs
MicrowaveGame/Assets/Resources/Scripts/Rooms/RoomGenerationBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Utilities/Extensions.cs

This PR adds the ability to change the spawn rates of rooms at various "depths" of the level generation. For example you could have a difficult room type have a 0.25x spawn chance up to 75% through the level but for the last 25% the spawn chance increases to 1x.
It also adds the ability to add "guaranteed spawns" which ensure that the room will spawn at least once for a given depth. This could be used to ensure an end-room spawns or that there is always a shop within the generated level.
- Added `GetRandomElementWithProbability` extension method (008e048)
- Added SpawnProbabilities to rooms for level generation (0e3e2cf)
- Added fail-safe for guaranteed rooms in level generation (3b5eab2) 
Open a room prefab, and play around with some SpawnProbability configurations on their …

Level generation adjustments

---

MicrowaveGame/Assets/Resources/Scenes/Hub.unity
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuNarrativeBehaviour.cs

Quick update, this is a fix for Kieran's original PR that updates narrative to Hub Scene
To Test, go from main menu to Hub Scene and check if three dialogue entries exist and doesn't mention Merlin as a microwave

Narrative update round 2

---

MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuControls.prefab
MicrowaveGame/Assets/Resources/Scenes/Gameplay.unity
MicrowaveGame/ProjectSettings/ProjectSettings.asset

Quick PR, changes and updates made to fix spelling and project settings, as well as drag in recent merges!

Jarryd bug testing

---

MicrowaveGame/Assets/Resources/Scenes/Hub.unity
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuInputBehaviour.cs

Got Keybind for escape working. required an else statement in the OnPause Function. Please make sure it works for you guys.

Fixed Escape Issue

---

MicrowaveGame/Assets/Resources/Inputs/InputActionManager.inputactions

ON Navigate in the Input manager for the Input System, I added a Hold interaction, and a   Stick Dead Zone Processor. I was going to manually code in their functionality, until I realised that these options were available.

Added Hold and Stick Dead Zone

---

MicrowaveGame/Assets/Resources/Scripts/Menus/MenuInputBehaviour.cs

Else if statement wasn't being called at all, so I added the switch menu statement to the accessible else if statement, and removed the dead code. Please verify it works for you.
To verify:
Pause game
Enter control menu
Press escape(should take you back to the pause menu)

Changed minor logic bug

---

MicrowaveGame/Assets/Resources/Prefabs/Enemies/EnemyZapper/EnemyZapperYellow.prefab

Zapper Enemy Particles Fix

---

MicrowaveGame/Assets/Resources/Scripts/HealthBehaviour.cs

Entities now have a red flash when being damaged. Please make sure it is visible.

Flash colour damage

---

MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialEHard.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialEHard.prefab.meta
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNHard.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNHard.prefab.meta
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialSHard.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialSHard.prefab.meta
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialWHard.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialWHard.prefab.meta

This branch adds four new ending rooms which have a 50% chance to spawn at the highest depth.
To Test

Harder ending rooms

---

MicrowaveGame/Assets/Resources/Prefabs/Inventory/InventoryInformationPanel.prefab
MicrowaveGame/Assets/Resources/Prefabs/Player/Player.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomTutorial/TutorialContinueNS.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomTutorial/TutorialEndNS.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomTutorial/TutorialStartN.prefab
MicrowaveGame/Assets/Resources/Scripts/Config/Configuration.cs
MicrowaveGame/Assets/Resources/Scripts/Inventory/InventorySelectedFloorItemBehaviour.cs

This PR adjusts the layering of the tutorial sprites.
To test, ensure the layering is correct.

Adjust tutorial sprite layering

---

MicrowaveGame/Assets/Resources/Prefabs/Projectiles/ProjectileBullet.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomTutorial/TutorialStartN.prefab
MicrowaveGame/Assets/Resources/Scenes/Hub.unity

Small PR for Arrow in First Tutorial Room

Updated Tutorial with Arrow for first room

---

MicrowaveGame/Assets/Resources/Scripts/Inventory/InventoryInformationPanelBehaviour.cs

Hopefully this fixes the lag in the tutorial room on release builds.
Create a build and see if it lags in the item room during the tutorial.

Tutorial lag fix
