JarrydWorland/2021_Capstone_GP2_Team

MicrowaveGame/Assets/Resources/Inputs/InputActionManager.inputactions
MicrowaveGame/Assets/Resources/Inputs/InputActionManager.inputactions.meta
MicrowaveGame/Packages/manifest.json
MicrowaveGame/ProjectSettings/ProjectSettings.asset

This PR enables and enforces Unity's new input system and includes a basic input actions file (f737cd5c46096b0f13bca59eee55ecf8189b7ebf).
There's no real test for this since it isn't used anywhere right now, but you can view the input actions file inside the `Resources/Inputs/` folder and you can view the input system setting at `Edit > Project Settings > Player > Active Input Handling`.

Enable Unity's new input system and create a basic input actions file

---

MicrowaveGame/Assets/Resources/Animations/Inventory/InventorySlotAnimationController.controller
MicrowaveGame/Assets/Resources/Scripts/Inventory/InventorySlotBehaviour.cs

The PR #53 added item animations, however it didn't account for the use item animation being a continuous looping animation. This PR fixes that.
To test, drag the player, item speed increase, and level prefabs into the root scene, and drag the inventory prefab onto the main camera. When you pick up and use the item, it should pulsate until the item has completed its use time. It should then play the drop item animation.

Fix use item animation

---

MicrowaveGame/Assets/Resources/Scripts/Items/ItemBehaviour.cs

Currently, any object that collides with an item will add it to the nearby item list. This PR changes this so only when the player is colliding with an item should it be added to the nearby item list.

Only allow nearby items to be added when colliding with the player

---

MicrowaveGame/Assets/Resources/Scripts/Hazards/HazardOilSpillBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Hazards/HazardSpikeBehaviour.cs

This PR ensures hazard collision is only done with the player.
To test, place hazards in the scene and ensure they all work correctly.

Ensure hazard collision is only done with the player

---

MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomBase.prefab
MicrowaveGame/Assets/Resources/Scripts/Rooms/RoomClearBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Rooms/RoomClearBehaviour.cs.meta

This PR allows items to be spawned when all enemies in the room have been defeated.
To test, add an enemy to a room prefab (easiest is "RoomPlatedNESW" since it's the spawn room) and ensure that an item is spawned when the enemy is defeated.

Spawn an item when all enemies in the room have been defeated

---

MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuMain.prefab
MicrowaveGame/Assets/Resources/Prefabs/Videos.meta
MicrowaveGame/Assets/Resources/Prefabs/Videos/VideoMenu.prefab
MicrowaveGame/Assets/Resources/Prefabs/Videos/VideoMenu.prefab.meta
MicrowaveGame/Assets/Resources/Scenes/Menu.unity
MicrowaveGame/Assets/Resources/Videos.meta
MicrowaveGame/Assets/Resources/Videos/VideoMainMenu.mp4.meta
MicrowaveGame/Assets/Resources/Videos/VideoRenderTexture.renderTexture
MicrowaveGame/Assets/Resources/Videos/VideoRenderTexture.renderTexture.meta

This PR adds a background video to the `Menu` scene.
To test, run the game and look at the main, controls (menu scene only), and credits menus and ensure the video is playing on each one.

Add background video to the menu scene

---

MicrowaveGame/Assets/Resources/Inputs/InputActionManager.inputactions
MicrowaveGame/Assets/Resources/Prefabs/Player/Player.prefab
MicrowaveGame/Assets/Resources/Scripts/Player/PlayerWeaponBehaviour.cs

This PR makes it so bullets will always be fired towards the current mouse position.
Additionally, it also fixes controller looking not working.
To test, launch the game and ensure the bullet is always fired towards the mouse, and for the controller, that the bullet is fired in the direction the right joystick is currently in.

Mouse and controller input adjustments

---

MicrowaveGame/Assets/Resources/Scripts/Utilities/Log.cs

This PR fixes the logging system using debug only information in runtime builds. It also removes the logging categories filtering window as it was decided searching for the category in the log was enough to filter the categories for our purposes.
-  Removed `EditorLogging` window and removed debug information and colors from release builds (030b4db)
Ensure the logging still displays correctly, and that the game runs correctly when building for a release.

Log system bug fixes

---

MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNE.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNEW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNS.prefab
README.md

This PR reflects changes in room design to fix potential movement bugs and issues around conveyor belts and hazards. 
**Changes Include**
([4035e3f](https://github.com/JarrydWorland/2021_Capstone_GP2_Team/commit/4035e3fa4f75cf3628a3e59d0cfdd72ff3e6ca41))
- Updated NS Room with accessible gap between conveyor belts
- Updated NE Room with gap to allow potential save between conveyor belt and spikes
- Updated NEW Room moving hazard and conveyor belt closer to center and potential save between conveyor belt and hazard
**Testing**
(Mouse/Keyboard or Controller)
Open up the Gameplay scene and check the prefabs for NS, NE and NEW so you know which rooms to look out for. Check player interaction between these conveyor belts and hazards to ensure movement accessibility or making it …

Conveyor Belt and Hazard Interaction Bug Fixes

---

MicrowaveGame/Assets/Resources/Scripts/Levels/LevelTraversalBehaviour.cs

This PR fixes the player being immediately teleported back into the previous room.
To test, walk through a bunch of doors and ensure the teleport back behaviour doesn't occur.

Move the player further into the room on traversal

---

MicrowaveGame/Assets/Resources/Scripts/Levels/LevelTraversalBehaviour.cs

The rooms were getting paused, but because Update() was getting called before the room was loaded to remove the previous room, the pause menu could be called because of the Resume function in Update. This was fixed by removing the Resume function from update, and moving it to after the player was moved.
Please verify that pressing pause on leaving rooms doesn't leave the timescale unchanged, on keyboard and controller.

Fixed Level Traversal logic error

---

MicrowaveGame/Assets/Resources/Scripts/Levels/LevelTraversalBehaviour.cs

This PR resolves the room transition issue.
As mentioned on the Trello card (see: https://trello.com/c/hQfUR4fN), even though #103 fixed the issue we were looking at, it undid the original intention behind it.
This finally resolves the issue by only resuming play after the room transition has finished if the menu is "MenuPlaying".
To test, pause the game as the room transitioning is underway. Enemies in the room shouldn't be animated / shooting and you shouldn't be able to move around. If you don't pause during a room transition, it should resume play once the transition is finished.

Only resume play after room transition if in the playing menu

---

MicrowaveGame/Assets/Resources/Prefabs/Hazards/HazardAcidSpill.prefab
MicrowaveGame/Assets/Resources/Prefabs/Items/ItemKeyCard.prefab
MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuCredits.prefab
MicrowaveGame/Assets/Resources/Scenes/Menu.unity
MicrowaveGame/ProjectSettings/ProjectSettings.asset

Testing have been completed for Version 0.1.4 to be built and released Saturday 18th September.  A full list of feedback can be found in #bug-report on Discord.
This PR has made a few modest changes to improve the player experience
**Change Include:**
- Added Narrative Dialogue to Key Card pickup about being teleported and informing the player the demo is complete
- Poison damage duration reduced from 5 to 2
- Fixed Credits screen to include missing team members
- (Project Setting Changed for current build)
**Testing:**
Changes have been made across the game, you'll need to playthrough it's entirety and take notice of poison damage, the credits screen on the Menu and the key card pickup dialogue

Bug Testing Fixes (v0.1.4)

---

MicrowaveGame/Assets/Resources/Scripts/Player/PlayerWeaponBehaviour.cs

This is a fix by adding the _lastMousePositionInWorld to a separate function that is called by Update of Player Weapon Behaviour.
Please make sure it works.

Added fix for Aim direction

---

MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialESW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialN.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNE.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNS.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNSW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNW.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialS.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialW.prefab

Concern was made around windows being assumed as doors if they are in the same place as doors generally are, this has now been modified to have all windows not be place in the middle of any four walls. 
**Changes Made**
- Rooms have been modified to have the windows off centre to not be confused with doors
**Testing**
Check the Room Prefab folder and check all windows are off-centre, then playing in-game to witness those changes

Windows in Room Prefabs modified

---

MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuControls.prefab
MicrowaveGame/Assets/Resources/Scenes/Gameplay.unity
MicrowaveGame/Assets/Resources/Scenes/Hub.unity
MicrowaveGame/Assets/Resources/Scenes/Menu.unity
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuControlsBehaviour.cs
MicrowaveGame/ProjectSettings/ProjectSettings.asset

This PR adds `Controller` and `Keyboard & Mouse` buttons to the top of the controls menu, where the `Controller` button shows the controller-specific controls, and the `Keyboard & Mouse` button shows the keyboard & mouse specific controls.
To test, launch the game and ensure the buttons show the correct content and that the content itself (i.e. bindings) are correct.

Add keyboard and mouse controls to controls menu

---

MicrowaveGame/Assets/Resources/Scenes/Gameplay.unity
MicrowaveGame/Assets/Resources/Scripts/Weapons/RapidFireWeaponBehaviour.cs

The Player Weapon has been updated to allow pitch modulation of the sound effect, applying a rnd float  to the pitch each time it is called.
**Changes**
- Gameplay Loop Music has been reenabled
- AudioManager has been updated to allow for pitch modulation to be added to a method call's parameter 
- Player Weapon has the pitch modulation applied 
**Testing**
Jump in game and shoot around the gameplay scene, you can hear different pitches of the weapon

Audio Updates - Pitch and Gameplay Loop

---

MicrowaveGame/Assets/Resources/Scripts/Menus/MenuBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuButtonBehaviour.cs

This PR fixes the menu indicator being off screen after changing menu and stops setting the default menu button after the first entry into a menu.
To test, launch the game and ensure that when you open, close, change room, and reopen the pause menu, the indicator is in the correct place.

Fix menu indicator positioning

---

MicrowaveGame/Assets/Resources/Scripts/Levels/LevelTraversalBehaviour.cs

Added a foreach loop to the LevelTraversalBehaviour script for each type of projectile available. I did this because If I did one at a time,   it ignores some projectiles.
Please make sure projectiles are destroyed on room transitions, both default and rapid fire.

Destroy Projectiles fix

---

MicrowaveGame/Assets/Resources/Scripts/Doors/DoorConnectionBehaviour.cs

Doors on close now no longer have an enable collider, and when opening them, they do have to reenable the disabled collider.
Please see if I missed an Issue.
Closed doors(N,S,E,W) Need to be checked for any sign of the collider sticking,
Open Doors(N,E,S,W(After Close) need to be checked if they can be passed through.

Added door Collider fix

---

MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomIndustrial/RoomIndustrialNE.prefab

In previous PR testing, I noticed the NE Spike Trap Room could cause the players to become over damaged and lose, to make it fairer, there is now just one collider
**Changes Made**
- Updated the Spike Trap Colliders in NE to have one active collider, instead of three
**Testing**
Jump into a game and encounter the NE Room with the three spike traps and conveyor belts

Fix Spike Trap Colliders

---

MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuControls.prefab

This PR fixes the whoopsie I made when I initially added the keyboard bindings listing to the controls menu.
To test, ensure the keyboard & mouse bindings listings in the controls menu is correct.

Fix keyboard bindings listing in controls menu

---

MicrowaveGame/Assets/Resources/Scenes/Gameplay.unity
MicrowaveGame/Assets/Resources/Scripts/Hazards/HazardAcidSpillBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Hazards/HazardOilSpillBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Hazards/HazardSpikeBehaviour.cs

I adjusted ground based hazards to only look for wheels, and by default, other hazards and enemies only look for the player.
Please check these hazards only hit Merlin's wheel:

Player collider adjustments

---

MicrowaveGame/Assets/Resources/Scripts/Camera/CameraPanBehaviour.cs.meta

This PR fixes the issue where building the game results in the camera showing nothing but  the HUD.
Build the game out and ensure the game plays properly.

Fixed camera breaking when building the game

---

MicrowaveGame/Assets/Resources/Scripts/Inventory/InventoryBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Inventory/InventorySlotBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Projectiles/ProjectileBehaviour.cs

This PR makes it so the swapping behaviour won't change the selected slot. Additionally, this also re-adds the player bullet collison particle effects that I had unknowingly broke in a previous PR.
Changes are:
* Re-add player bullet collision particle effects (e435d60931af2463112921579771c4c5054161fe).
* Don't change the selected slot if we're swapping items (0633ead30e9ec89d57a4b7ec8cdf40ffabcb4e11).
To test, fill the player's inventory and attempt to pick up another item on any slot other than the first. The selected slot indicator should not move. Additionally, ensure the player bullet collision particle effects now work again when colliding with walls.

Item swapping behaviour fix

---

MicrowaveGame/Assets/Resources/Prefabs/Items/ItemHealthIncrease.prefab
MicrowaveGame/Assets/Resources/Prefabs/Rooms/RoomHub/RoomHubSW.prefab
MicrowaveGame/Assets/Resources/Scenes/Hub.unity
MicrowaveGame/Assets/Resources/Scripts/CardCountDisplayBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/CardCountDisplayBehaviour.cs.meta
MicrowaveGame/Assets/Resources/Scripts/DungeonEntrance/DungeonEntranceBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Items/ItemKeyCardBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Levels/LevelGenerationBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Persistent.cs
MicrowaveGame/Assets/Resources/Scripts/Utilities/Extensions.cs

Supersedes #177 
This PR implements a card counter that is only visible in the hub scene. Additionally, it adds a chevron to the hub floor that only shows when  the ending door is open.
Note that collecting more cards than the required number to open the ending door is intended (i.e. 4/3 cards).
To test, ensure the card counter only shows in the hub scene. Also ensure that the counter increases once card is collected.

Add key card count display

---

MicrowaveGame/Assets/Resources/Prefabs/Items/ItemKeyCard.prefab
MicrowaveGame/Assets/Resources/Prefabs/Items/ItemProjectileSize.prefab
MicrowaveGame/Assets/Resources/Prefabs/Items/ItemSpeedIncrease.prefab
MicrowaveGame/Assets/Resources/Prefabs/Items/TutorialItemHealthIncrease.prefab
MicrowaveGame/Assets/Resources/Scenes/Hub.unity
MicrowaveGame/Assets/Resources/Scripts/Items/ItemProjectileSizeBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuNarrativeBehaviour.cs

This PR contains some minor fixes, including:
* Adjustments to item descriptions and missing item pickup sound effects (164c3c231d2ec5857f4feaed1481c233298df309).
* Adding a dialgoue for when the player returns to the hub with enough key cards to open the ending door (f8e1a3f106c5b9fbc9129ec14c4bab489ed89f13).
To test, ensure that item descriptions read okay, and that all items have a pickup, and a drop sound effect. Also ensure that the new dialogue only shows when the player has exactly enough cards to open the door. If they have more (i.e. 4/3), it should not show when they return to the hub.

Minor fixes

---

MicrowaveGame/Assets/Resources/Scripts/Config/Configuration.cs

This PR makes it so tutorial sprites are always updated upon entering the hub scene.
To test, ensure tutorial sprites are set correctly when entering the hub scene.

Force tutorial sprites to update when entering the hub scene

---

MicrowaveGame/Assets/Resources/Scenes/Hub.unity
MicrowaveGame/Assets/Resources/Scripts/Rooms/RoomEndGameBehaviour.cs

Changes Made
- Altered the dialogue in DialogueContentBehaviour on CardCountDisplay
How to Observe
- Go to Canvas/CardCountDisplay/DialogueContentBehaviour in the Hub scene to see the new dialogue
- Alternatively, collect three keycards in-game to meet the dialogue trigger

Changed the end of game dialogue content

---

MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuGameOver.prefab
MicrowaveGame/Assets/Resources/Prefabs/Menus/MenuGameOver.prefab.meta
MicrowaveGame/Assets/Resources/Scenes/Gameplay.unity
MicrowaveGame/Assets/Resources/Scripts/Items/ItemKeyCardBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuGameOverBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/Menus/MenuGameOverBehaviour.cs.meta
MicrowaveGame/Assets/Resources/Scripts/StatisticsTrackerBehaviour.cs
MicrowaveGame/Assets/Resources/Scripts/StatisticsTrackerBehaviour.cs.meta
MicrowaveGame/ProjectSettings/ProjectSettings.asset

This PR adds the game over screen that shows when you collect a key card, showing statistics like time taken, rooms explored percentage, etc.
To test, collect a key card and validate the information is correct.

Game over screen

---

MicrowaveGame/Assets/Resources/Scripts/Menus/MenuMainBehaviour.cs

Currently the opening cut-scene plays every time you press play, so if you play, return to main menu and play again it will replay the cut-scene. This PR changes it so it only plays the first time the user hits play (per game launch).
Ensure that returning to main menu and pressing play again takes you straight to the hub.

The opening cutscene now only plays once

---

MicrowaveGame/Assets/Resources/Prefabs/Items/ItemKeyCard.prefab

Just a small change to bring the pick up key card dialogue in line with other dialogue.
To test, make sure key card is refered to as "key card" everywhere and not "keycard". Also make sure the power grid is refered to as the "power grid" and not anything else. Finally, make sure the Lightbulb Gang has proper capitalisation like "Lightbulb Gang".

Update key card dialogue to be consistent with other dialogue
